import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Background from "@/components/Background"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],   // required
  weight: ["400", "500", "700"], // optional: choose the weights you need
});

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Background>
          {children}
        </Background>
      </body>
    </html>
  );
}
